### PR TITLE
2.0 rc

### PR DESCRIPTION
**Pull request by zkamvar**
I believe this version is stable with clear documentation.

These represent the major changes from version 2.0

The best option, perhaps, is to compare the NEWS diff.

Cool things to happen:

- bootstrap diversity stats
- interactive minimum spanning networks
- pairwise index of association
- a new vignettes for multilocus genotypes
- genclone and snpclone objects retain memory of distance, threshold, and algorithm used for filtering.

It would be nice if people would kick the tires a little bit and make sure that things like documentation are clear.

### CODE REVIEW

**Comment by zkamvar** [comment]
To be clear: I need at least two people to glance at this and tell me it's okay.

I'm looking at you, @zachary-foster, @Tabima, @knausb, @grunwald

**Comment by zachary-foster** [comment]
Sure, I will look it over today.

**Comment by zkamvar** [comment]
Thanks, Zach. I need to submit it today, so the sooner the better.

**Comment by zachary-foster** [comment]
Ok, Im working on it now.

**Comment by zachary-foster** [comment]
Here is what I have noticed so far. I skimmed over the documentation to look for spelling errors mostly since im not all that familiar with the logic/purpose of the package. I can dig into it more, but I am reaching the point of diminishing returns. Most of the comments below are rather minor: 

* The following files do not have the license at the start that the rest do: `aaMLGclass.R`, `aaaMLGmethods.R`, `filter_stats.R`, `poppr.R`
* Mixture of `.r` and `.R` extensions in `R/`
* "univariate" or "unvarying" in  `R/data_subset.r:#' @param drop \code{logical}. If \code{TRUE}, unvariate alleles will be dropped` ?
* A few typos (fixed in my commit)

**Comment by zachary-foster** [comment]
I looked over the MSN vignette and the imsn function and they make sense to me. 
The imsn function example worked fine for me and I was able to figure it out pretty fast. 
I like the tab that shows the code to execute the current configuration; very useful.
I made a few changes to wording and inserted a few comments, but nothing major; my wording changes are suggestions more than anything else. 
Is there anything else you want me look over specifically?

**Comment by zkamvar** [comment]
That should be about it. I'm reading through your comments on the vignette right now. Thanks for being thorough!

**Comment by zkamvar** [comment]
I'm keeping the `function()` type of syntax in text because the parentheses allow you to see that I am referring to a function explicitly.

**Comment by Tabima** [comment]
Like I told Zhian: I took a look at the `mlg.R` and `how_to_migrate.pdf` vignettes and they look good. I was taking the apporach of a naive user and incidentally got surprised at the changes and the good implementation of these for the easy understanding of the user. I can look at more files if needed! :smiley:

**Comment by zachary-foster** [comment]
Since you are using `function()` notation for `mlg.filter`, you should probably use it for the rest of the functions mentioned, such as  `diversity_ci` and `diversity_boot`. A regex find using "`[a-zA-Z_]+`" helped me find functions without parentheses. 
I agree about repeating when important.

**Comment by zkamvar** [comment]
Good point.

**Comment by zkamvar** [comment]
I will merge this when everything seems to be clear.

**Pull request merged**
