### PR TITLE
Update bitwise.r

### PR DESCRIPTION
**Pull request by knausb**
Corrected stated lower bound of IA and its interpretation.

### CODE REVIEW

**Comment by zkamvar** [comment]
Some nitpicks:

1. When you reference a function, please wrap it in `\code{\link{fun}}` so that it links to the man page for that function.

2. Can you process the documentation with roxygen?

Yes, the value of rbarD does take -1 to 1, but I think it's also important to note that significantly negative values are not often seen and can be difficult to interpret. Slightly negative values are often interpreted as being in linkage equilibrium.

**Comment by knausb** [comment]
When I process the docs with roxygen I get:

Skipping invalid path:  .PA.Ia.Rd.Rd 

But that was there when I forked the repo.

Would it be accurate to interpret rbarD as a correlation coefficient (e.g., r)? As it approaches 1 there is correlation for the same state while negative one may be for opposite states?

I've wrapped the function references with \link{} but will wait for your reply before making another pull request.

**Comment by zkamvar** [comment]
> When I process the docs with roxygen I get:
> 
> Skipping invalid path: .PA.Ia.Rd.Rd
> 
> But that was there when I forked the repo.

Yes, that's an artifact of an internal function ending in `.Rd`

> 
> Would it be accurate to interpret rbarD as a correlation coefficient (e.g., r)? As it approaches 1 there is correlation for the same state while negative one may be for opposite states?
> 

It would be most accurate to interpret rbarD as described in [Agapow and Burt, 2001](http://dx.doi.org/10.1046/j.1471-8278.2000.00014.x) (which they do describe it as a correlation coefficient 😝 ). It's kind of strange, though. Positive correlation makes sense when regarding multilocus linkage disequilibrium, but what the hell does negative correlation mean? Again, negative values are not often seen and I would be reticent to place an interpretation on the calculation run on thousands of loci. 

> I've wrapped the function references with \link{} but will wait for your reply before making another pull request.

I'm assuming you mean `\code{\link{}}`?
Additionally, you don't have to make another pull request. If you continue to make commits on your fork, they will show up here. 

In the future, before making a pull request, it's best to make changes on a new branch; this avoids conflicts when updating your fork.

**Comment by zkamvar** [comment]
Also, let me know if you would like some clarification about how GitHub flow works 😃

**Comment by zkamvar** [comment]
I will accept this PR, but I will likely change the language to emphasize the usual interpretation (null = 0, linked > 0) first and then stating the theoretical range of the index

**Pull request merged**
