### PR TITLE
Update for travis changes

### PR DESCRIPTION
**Pull request by jimhester**

### CODE REVIEW

**Comment by jimhester** [comment]
@zkamvar This updates you .travis.yml to use the container based infrastructure and turns on package caching. The first build will be slow when using the cache as the packages need to be built from source. But subsequent builds will be much faster as the dependencies do not need to be rebuilt.

FWIW the LaTeX package that was missing was `natbib`. I am not sure why the error message was not pointing to that package.

**Comment by jimhester** [comment]
Actually looking at this a little more it looks like natbib is already installed as well. The issue you were having was caused by installing the `latex-xcolor` and `texlive-latex3` packages which were overriding the home directory latex R travis now installs. Removing those is what fixed the build.

**Comment by zkamvar** [comment]
Thanks for the fix! For reference, is there a changelog for the R travis builds?

**Comment by jimhester** [comment]
There is no changelog, but you can look at the commits to the ruby script that generates the shell script which is run for R builds. https://github.com/travis-ci/travis-build/commits/master/lib/travis/build/script/r.rb

**Pull request merged**
