### PR TITLE
Added popNames to popsub example

### PR DESCRIPTION
**Pull request by knausb**
This is a second attempt at #165 which broke the man pages somehow. Fingers crossed.

### CODE REVIEW

**Comment by zkamvar** [comment]
If we merge this, it should be fine as long as I roxygen it afterwards. If you roxygen it now, I'll have to reject it. The parent commit to the one you proposed is still from 14 months ago.

**Comment by knausb** [comment]
Hmm, I thought I had used a parent commit that was updated on Dec. 31. Sorry about that.

**Comment by zkamvar** [comment]
No worries. It takes practice. Would you like me to merge this commit, or would you like to attempt adding a branch from the most recent commit and building the docs?

**Comment by knausb** [comment]
I had problems building the docs on my end. But I doubt that has to do with your code. If you see this change as acceptable I think you should merge it. Thanks!

**Comment by zkamvar** [comment]
I think the change is perfectly acceptable. I do have some ideas as to why you were experiencing trouble building docs if you would like to hear them sometime :)

**Comment by knausb** [comment]
Thanks Zhian! And thanks for your offer to help sort out the doc building issue. Its something I've ran into before, but don't remember the solution. And I was starting to feel like I was investing a whole afternoon in proposing a two line change. For now I think I'm happy hoping it won't be there next time I try.

**Comment by zkamvar** [comment]
> For now I think I'm happy hoping it won't be there next time I try.

My suggestion would be to just delete your fork and re-fork when you need it. Either that, or fetch upstream, rebase the master branch, and push your local copy before you make an edit.

**Comment by knausb** [comment]
Delete and fork is my usual choice. It may lack elegance, but there's usually something positive about deleting something. And I thought I did that in this PR. Not sure how I managed to munge it. I'll have a few new things to look for now before I try to make another PR. Thanks!

**Pull request merged**
