### PR TITLE
added popNames() step to popsub example

### PR DESCRIPTION
**Pull request by knausb**
The function `popsub()` requires a vector of population names for either `sublist` or `blacklist`. I've added an example that reminds us how to accomplish this as part of the `popsub()` examples.

### CODE REVIEW

**Comment by zkamvar** [comment]
Thanks for this Brian. I like the push for clarity.

I'm going to reject this at the moment because of duplicate entries in some of the man files (probably due to merge commits). Please re-try with an up-to-date branch.

**Comment by zkamvar** [comment]
As a reminder, here's how you can accomplish this on the command line (assuming you already have your fork setup to track grunwaldlab/poppr as upstream and you haven't added anything to the master branch):

```
git fetch upstream
git rebase upstream/master
git push
git checkout -b my-new-branch
```

**Comment by knausb** [comment]
Just validating that some part of the Roxygen2 magic stopped working and that I've managed to break the docs. I'll try again.

**Comment by zkamvar** [comment]
To clarify, the man pages were broken due to merge conflicts, not Roxygen2. The error happened when the man pages were built before merging 14 months of commits (https://github.com/grunwaldlab/poppr/pull/165/commits/decab9b7eb8bd3b02b735c5409decaba98ee4389#diff-465945af4b596687499f4fcf930f0d65). The resulting merge of the master branch inadvertently duplicated some entries.

**Pull request closed without merging**
